---
# file uwsgi/tasks/main.yml

# Install uWSGI from pip (by default) and configure it in Emperor mode

# http://uwsgi-docs.readthedocs.org/en/latest/WSGIquickstart.html
# to see other install methods

- name: install uwsgi dependencies
  apt:
    pkg: "{{ item }}"
    state: present
  with_items:
    - build-essential
    - python-dev

# the python role has a task to install a package to a venv, but we're installing globally.
# this changes if we want to use a newer version of python than system default (currently 2.7.6)
# alternatively, use a "system wide" virtualenv that we'd then activate when calling init/upstart
- name: install uwsgi with pip globally
  pip:
    name: uwsgi
    state: latest

- name: Ensure the uwsgi config directory exists
  file:
    state: directory
    path: "{{ uwsgi_config_dir }}"
    owner: root
    group: root
    mode: 0755

- name: Create the Emperor ini file
  template:
    src: emperor.ini.j2
    dest: "{{ uwsgi_config_dir }}/emperor.ini"
    owner: root
    group: root
    mode: 0644

- name: Create the Vassal directory for uWSGI in Emperor mode
  file:
    state: directory
    path: "{{ emperor_vassal_dir }}"
    owner: root
    group: root
    mode: 0755

- name: UWSGI should start with the OS
  template:
    src: upstart.emperor.conf.j2
    dest: "{{ uwsgi_upstart_file }}"
    owner: root
    group: root
    mode: 0644
    # TODO: re-enable when https://github.com/ansible/ansible/issues/10152 is addressed
    #validate: "init-checkconf %s"

- name: Make sure UWSGI is running
  service:
    name: "{{ uwsgi_upstart_name }}"
    state: started
    enabled: yes

