---
# file: uwsgi/tasks/vassal.yml

#todo: Make sure you're loading the vars file default/main.yml
#- include_vars: main.yml

- name: Ensure the Vassal config directory exists
  file:
    state: directory
    path: "{{ vassal_config_dir }}"
    owner: root
    group: root
    mode: 0755

- name: Create a uWSGI vassal ini file
  template:
  # Need to determine if this file already exists, otherwise the default will continuously get overridden
  #   Maybe raise huge warnings or fail out if app_name isn't set?
    src: vassals/vassal.ini.j2
    dest: "{{ vassal_config_dir }}/{{app_name}}.ini"
    owner: root
    group: root
    mode: 0644

# uwsgi/tasks/main installs uwsgi and sets up an emperor.
# make sure that the service is started/running to prevent surprises
- name: Make sure UWSGI is running
  service:
    name: "{{ uwsgi_upstart_name }}"
    state: started
    enabled: yes



